# Generated by Django 6.1 on 2026-08-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeowner_names', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('property_address', models.CharField(max_length=255)),
                ('roof_age', models.CharField(blank=True, max_length=100)),
                ('known_issues', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('time_label', models.CharField(help_text='Display label for the slot, e.g. "2:00 PM".', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='portfolioapp.inspectionrequest')),
            ],
            options={
                'ordering': ['date', 'time_label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('date', 'time_label'), name='unique_scheduled_slot')],
            },
        ),
    ]
