# Generated by Django 6.1 on 2026-08-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_1h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_24h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrequest',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email only'), ('text', 'Text only'), ('both', 'Both email and text')], default='email', help_text='How the homeowner wants booking confirmations and reminders sent.', max_length=10),
        ),
    ]
